### ISSUE TITLE
Remove the curl dependency and use the guzzle beast

### ISSUE THREAD

**Issue by naveenvalecha** [keycdn/php-keycdn-api#5]
Reference : https://www.drupal.org/project/purge_purger_keycdn

We wrote the purger for the keycdn for the integeration module. We used this libary but opt out later as it was using the curl magic internally. As curl is not much robust itself so we shifted to our own requests.

Use the guzzle and let the library ride on it.

**Comment by svenba** [comment]
We don't plan to replace curl at the moment.
