### ISSUE TITLE
Make the library dependent on php 5.5+

### ISSUE THREAD

**Issue by naveenvalecha** [keycdn/php-keycdn-api#6]
As the php5.5 already EOL so the library should itself sends a positive feedback to end users to use the supported php version. So update the required version to above or equal to 5.5. As there are still couple of *AMP stacks have the php5.5 Also OSx default still have 5.5 
https://github.com/keycdn/php-keycdn-api/blob/master/composer.json#L12

See , http://php.net/supported-versions.php

Thanks!

**Comment by svenba** [comment]
We will consider doing this. Thanks.

**Comment by naveenvalecha** [comment]
Could we leave this open to keep a track or the updates on the feature request. or should I file another feature Request ?
